### PR TITLE
add mplhep and hist

### PR DESCRIPTION
**Pull request by andrzejnovak**

### CODE REVIEW

**Review by matthewfeickert — APPROVED** [review]
LGTM

**Comment by matthewfeickert** [comment]
Though maybe we can also add a link to https://github.com/andrzejnovak/iris_hep_analysis_training_mplhep_2024 in the README?

**Comment by matthewfeickert** [comment]
@andrzejnovak Maybe

```diff
diff --git a/README.md b/README.md
index cfe7589..66b2ab0 100644
--- a/README.md
+++ b/README.md
@@ -19,7 +19,7 @@ This two day event plans to discuss:
 
 - Columnar analysis and uproot
 - Distributed analysis and Dask
-- Data Visualization techniques and libraries
+- [Data Visualization techniques and libraries](https://github.com/andrzejnovak/iris_hep_analysis_training_mplhep_2024)
 - Coffea columnar analysis framework
 - The Coffea-Casa analysis facility
 - Statistical tools
```

?

**Comment by alexander-held** [comment]
I think that makes sense.

**Review by matthewfeickert — CHANGES_REQUESTED** [review]
@andrzejnovak Maybe

```diff
diff --git a/README.md b/README.md
index cfe7589..66b2ab0 100644
--- a/README.md
+++ b/README.md
@@ -19,7 +19,7 @@ This two day event plans to discuss:
 
 - Columnar analysis and uproot
 - Distributed analysis and Dask
-- Data Visualization techniques and libraries
+- [Data Visualization techniques and libraries](https://github.com/andrzejnovak/iris_hep_analysis_training_mplhep_2024)
 - Coffea columnar analysis framework
 - The Coffea-Casa analysis facility
 - Statistical tools
```

for people that want to get to it without cloning this repo first?

**Comment by matthewfeickert** [comment]
@andrzejnovak Alternatively we can just commit your repos to a `mplhep/` directory. Can you do that and remove the submodule? (I don't have the ability to push to your fork, else I would make these changes)

**Pull request closed without merging**
